//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stillasEntities : DbContext
    {
        public stillasEntities()
            : base("name=stillasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingLinje> BookingLinjes { get; set; }
        public virtual DbSet<Bruger> Brugers { get; set; }
        public virtual DbSet<DemoAnsvarlig> DemoAnsvarligs { get; set; }
        public virtual DbSet<Konfiguration> Konfigurations { get; set; }
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Maskine> Maskines { get; set; }
        public virtual DbSet<MaskineKonfiguration> MaskineKonfigurations { get; set; }
        public virtual DbSet<ModelNavn> ModelNavns { get; set; }
        public virtual DbSet<Sælger> Sælger { get; set; }
        public virtual DbSet<Transportør> Transportør { get; set; }
        public virtual DbSet<Værksted> Værksted { get; set; }
    }
}
