//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingLinjes = new HashSet<BookingLinje>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> KundeID { get; set; }
        public Nullable<int> SælgerID { get; set; }
        public Nullable<int> VærkstedID { get; set; }
        public Nullable<int> DemoAnsvarligID { get; set; }
        public Nullable<int> TransportørID { get; set; }
        public Nullable<System.DateTime> LeveringsDato { get; set; }
        public Nullable<System.DateTime> AfhentningsDato { get; set; }
        public string Leverandør { get; set; }
        public string BeskedTilVærksted { get; set; }
        public string BeskedTilFølgeSeddel { get; set; }
    
        public virtual DemoAnsvarlig DemoAnsvarlig { get; set; }
        public virtual Kunde Kunde { get; set; }
        public virtual Sælger Sælger { get; set; }
        public virtual Transportør Transportør { get; set; }
        public virtual Værksted Værksted { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingLinje> BookingLinjes { get; set; }
    }
}
