//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        public int ID { get; set; }
        public string Navn { get; set; }
        public string Adgangskode { get; set; }
        public string AccessLevel { get; set; }
    
        public virtual DemoAnsvarlig DemoAnsvarlig { get; set; }
        public virtual Sælger Sælger { get; set; }
        public virtual Transportør Transportør { get; set; }
        public virtual Værksted Værksted { get; set; }
    }
}
